name: hanzo
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Andres Araujo <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  command_wrapper: ^0.2.0

dev_dependencies:
  test: ^0.12.0
  grinder: ^0.8.0+3
