name: hanzo
description: A library to easily use git hooks from Dart.
version: 1.0.0
homepage: https://github.com/andresaraujo/hanzo
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: '>=2.0.0-dev.48 <3.0.0'

dependencies:
  args: ^1.5.0
  io: ^0.3.3
  build_cli: ^1.0.0
  build_cli_annotations: ^1.0.0

dev_dependencies:
  build_runner: ^0.10.0
  test: ^1.3.0
  grinder: ^0.8.3
